const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const proofFile=path.join(require('node:os').tmpdir(),`arm112-sip-proof-${process.pid}.json`);const assert=require('node:assert/strict');
(async()=>{const base='http://localhost:8000';const login=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin',password:process.env.ADMIN_PASSWORD||'admin12345'})}).then(r=>r.json());const headers={'content-type':'application/json',authorization:'Bearer '+login.token};const stale=await fetch(base+'/api/users',{headers}).then(r=>r.json());for(const u of stale.filter(u=>u.username.startsWith('sip_proof_'))){const l=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:u.username,password:'Proof-password-12345'})}).then(r=>r.json());const sh={'content-type':'application/json',authorization:'Bearer '+l.token};const active=await fetch(base+'/api/active-run',{headers:sh}).then(r=>r.json());if(active?.run_id)await fetch(base+`/api/runs/${active.run_id}/skip`,{method:'POST',headers:sh});const r=await fetch(base+`/api/users/${u.id}`,{method:'DELETE',headers});if(!r.ok)console.log('Cleanup status',u.id,r.status);}if(process.env.CLEANUP_ONLY)return;const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});const context=await browser.newContext({permissions:['microphone']});const admin=await context.newPage();const users=[];const pages=[];let adminToken;try{await admin.goto('http://localhost:8000');adminToken=await admin.evaluate(async()=>{const login=await api('/api/login',{method:'POST',body:JSON.stringify({username:'admin',password:process.env.ADMIN_PASSWORD||'admin12345'})});state.token=login.token;state.role='admin';return login.token;});
const stamp=Date.now();for(let i=0;i<Number(process.env.CALLS||20);i++){const name=`sip_proof_${stamp}_${i}`;const u=await admin.evaluate(async name=>api('/api/users',{method:'POST',body:JSON.stringify({username:name,password:'Proof-password-12345',role:'student'})}),name);users.push({...u,name});}
const results=await Promise.all(users.map(async(u,index)=>{const userContext=await browser.newContext({permissions:['microphone']});const page=await userContext.newPage();pages.push(page);page.on('pageerror',e=>console.log('Browser diagnostic',index,e.message));await page.goto('http://localhost:8000');await page.addInitScript(()=>{});await page.evaluate(async({name,index})=>{const result=await api('/api/login',{method:'POST',body:JSON.stringify({username:name,password:'Proof-password-12345'})});state.token=result.token;state.role='student';state.username=name;const scenarios=await api('/api/scenarios');state.scenarios=scenarios;const scenario=scenarios.find(s=>s.title.includes('SMS · человек'));const run=await api(`/api/runs/${scenario.id}/start`,{method:'POST'});await restoreRun(run);sipRun=run.run_id;await connectSip();sipUA.on('newRTCSession',e=>{if(e.originator==='remote')e.session.answer({mediaConstraints:{audio:index===0,video:false},pcConfig:{iceServers:sipIceServers}});});},{name:u.name,index});await page.waitForFunction(()=>sipUA?.isRegistered(),{},{timeout:30000});if(index===0){const hardware=await page.evaluate(()=>api('/api/telephony/account?device=hardware',{method:'POST'}));fs.writeFileSync(proofFile,JSON.stringify(hardware),{mode:0o600});}
return page;}));
require('node:child_process').execFileSync('python3',[path.join(__dirname,'udp-register.py'),proofFile],{stdio:'inherit'});
await Promise.race([Promise.all(results.map(page=>page.evaluate(()=>api(`/api/telephony/runs/${state.runId}/call`,{method:'POST'})))),new Promise((_,reject)=>setTimeout(()=>reject(Error('Origination request timeout')),15000))]);
let media=[];const deadline=Date.now()+90000;
while(Date.now()<deadline){media=await Promise.race([Promise.all(results.map(p=>p.evaluate(async()=>{if(!sipSession?.connection)return {bytes:0,packets:0,established:false};const stats=[...(await Promise.race([sipSession.connection.getStats(),new Promise((_,reject)=>setTimeout(()=>reject(Error('RTP stats timeout')),3000))])).values()];const streams=stats.filter(x=>x.type==='inbound-rtp'&&x.kind==='audio');return {bytes:streams.reduce((n,x)=>n+(x.bytesReceived||0),0),packets:streams.reduce((n,x)=>n+(x.packetsReceived||0),0),established:sipSession.isEstablished()};}))),new Promise((_,reject)=>setTimeout(()=>reject(Error('Browser media probe timeout')),10000))]);if(media.every(x=>x.bytes>0&&x.packets>0&&x.established))break;await new Promise(resolve=>setTimeout(resolve,500));}
console.log('RTP diagnostic',JSON.stringify(media));assert(media.every(x=>x.bytes>0&&x.packets>0&&x.established));
console.log(`SIP: ${media.length} concurrent established WebRTC calls with inbound RTP audio PASS`);
const first=results[0];await first.evaluate(()=>{sipSession.mute({audio:true});if(!sipSession.isMuted().audio)throw Error('Mute failed');sipSession.unmute({audio:true});sipSession.hold();});await first.waitForFunction(()=>sipSession.isOnHold().local);await first.evaluate(()=>sipSession.unhold());await first.waitForFunction(()=>!sipSession.isOnHold().local);console.log('SIP: microphone mute/unmute and hold/resume PASS');
await Promise.all(results.map(p=>p.evaluate(async()=>{if(sipSession)sipSession.terminate();})));await first.waitForFunction(()=>!sipSession);await first.evaluate(()=>dialTraining('101'));await first.waitForFunction(()=>sipSession?.isEstablished(),{},{timeout:30000});await first.waitForFunction(async()=>[...(await sipSession.connection.getStats()).values()].some(x=>x.type==='inbound-rtp'&&x.kind==='audio'&&x.bytesReceived>0),{},{timeout:30000});console.log('SIP: outgoing call to voiced training dispatcher 101 with RTP PASS');await first.evaluate(()=>sipSession.terminate());
const bench=await first.evaluate(async()=>{await api('/api/questionnaires');const times=await Promise.all(Array.from({length:100},async()=>{const t=performance.now();const r=await api('/api/questionnaires');if(r.cards.length!==24)throw Error('Invalid catalogue');return performance.now()-t;}));times.sort((a,b)=>a-b);return {requests:times.length,p50_ms:Math.round(times[49]),p95_ms:Math.round(times[94]),max_ms:Math.round(times.at(-1))};});console.log('100 concurrent catalogue requests:',JSON.stringify(bench));fs.writeFileSync(process.env.RESULT_FILE||path.join(require('node:os').tmpdir(),'arm112-sip-proof-result.json'),JSON.stringify({calls:results.length,rtp:true,hold:true,outgoing:true,catalogue:bench},null,2));
await new Promise(resolve=>setTimeout(resolve,5000));
}finally{for(let i=0;i<pages.length;i++){try{const calls=await pages[i].evaluate(()=>state.runId?api(`/api/telephony/runs/${state.runId}`):[]);console.log('Call diagnostic',i,JSON.stringify(calls));}catch{}}for(const p of pages){try{await p.evaluate(async()=>{if(sipSession)sipSession.terminate();if(state.runId)await api(`/api/runs/${state.runId}/skip`,{method:'POST'});if(sipUA)sipUA.stop();});}catch{}}for(const u of users){try{await admin.evaluate(async id=>api(`/api/users/${id}`,{method:'DELETE'}),u.id);}catch(e){console.log('Cleanup needs retry for user',u.id);}}try{await admin.evaluate(async()=>{const login=await api('/api/login',{method:'POST',body:JSON.stringify({username:'student',password:process.env.STUDENT_PASSWORD||'student12345'})});state.token=login.token;await api('/api/telephony/account',{method:'POST'});});}catch{}await browser.close();try{fs.unlinkSync(proofFile);}catch{}}})().catch(e=>{console.error(e);process.exitCode=1});
