[training]
exten => 900,1,Answer()
 same => n,Echo()
 same => n,Hangup()
[training-playback]
exten => s,1,Answer()
 same => n,Set(CHANNEL(language)=ru)
 same => n,MixMonitor(/media/recording-${ARM_RUN_ID}.wav)
 same => n,Playback(/media/${ARM_SOUND})
 same => n,Wait(2)
 same => n,Hangup()
