[global]
type=global
user_agent=ARM112-Training
default_from_user=arm112
default_realm=arm112.local
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0
#include /provision/users.conf
